import re
from typing import Protocol


class Cursor(Protocol):
    """Minimal typed view of a SQL warehouse cursor shared by the SQL branch backends.

    The connectors (snowflake, databricks) are imported lazily and ship no usable types,
    so this Protocol gives the backends real types for the calls they make instead of Any."""

    def execute(self, sql: str) -> object: ...

    def fetchone(self) -> tuple[object, ...] | None: ...

    def fetchall(self) -> list[tuple[object, ...]]: ...


class Connection(Protocol):
    """A SQL warehouse connection that hands out cursors and can be closed."""

    def cursor(self) -> Cursor: ...

    def close(self) -> None: ...


def ident(name: str) -> str:
    """Validate a single SQL identifier before interpolating it into DDL.

    Branch names are generated by us, but the source name passed on the CLI is not, so
    reject anything that is not a plain identifier to avoid malformed or injected SQL."""
    if not re.fullmatch(r"[A-Za-z0-9_]+", name):
        raise ValueError(f"unsafe SQL identifier: {name}")
    return name
